AllCops:
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/map-reduce-ruby.rb

Style/StringConcatenation:
  Exclude:
    - spec/**/*.rb

Lint/UnreachableLoop:
  Exclude:
    - spec/**/*.rb

Metrics/BlockLength:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 250

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/ObjectThen:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/RedundantEach:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false
