name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", "3.1", "3.2"]
        redis:
          - redis:5.0
          - redis:6.0
          - redis:7.0
    services:
      redis:
        image: ${{ matrix.redis }}
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/cache@v1
      id: cache
      with:
        path: vendor/bundler
        key: ${{ hashFiles('Gemfile.lock') }}-${{ matrix.ruby }}
    - run: |
        bundle config set --local path "vendor/bundler"
        bundle install
        bundle exec rspec
        bundle exec rubocop
